// Code generated by "stringer -type=ResourceType"; DO NOT EDIT.

package storageconn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceCode-0]
	_ = x[CompiledBinary-1]
	_ = x[Test-2]
	_ = x[Checker-3]
	_ = x[Interactor-4]
}

const _ResourceType_name = "SourceCodeCompiledBinaryTestCheckerInteractor"

var _ResourceType_index = [...]uint8{0, 10, 24, 28, 35, 45}

func (i ResourceType) String() string {
	if i < 0 || i >= ResourceType(len(_ResourceType_index)-1) {
		return "ResourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[i]:_ResourceType_index[i+1]]
}
