// Code generated by "stringer -type=JobType"; DO NOT EDIT.

package invokerconn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompileJob-1]
	_ = x[TestJob-2]
}

const _JobType_name = "CompileJobTestJob"

var _JobType_index = [...]uint8{0, 10, 17}

func (i JobType) String() string {
	i -= 1
	if i < 0 || i >= JobType(len(_JobType_index)-1) {
		return "JobType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _JobType_name[_JobType_index[i]:_JobType_index[i+1]]
}
