// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package resource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownDataType-0]
	_ = x[Problem-1]
	_ = x[Submission-2]
}

const _DataType_name = "UnknownDataTypeProblemSubmission"

var _DataType_index = [...]uint8{0, 15, 22, 32}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
