// Code generated by "stringer -type=Type"; DO NOT EDIT.

package resource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceCode-0]
	_ = x[CompiledBinary-1]
	_ = x[CompileOutput-2]
	_ = x[Test-3]
	_ = x[Checker-4]
	_ = x[Interactor-5]
}

const _Type_name = "SourceCodeCompiledBinaryCompileOutputTestCheckerInteractor"

var _Type_index = [...]uint8{0, 10, 24, 37, 41, 48, 58}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
