// Code generated by "stringer -type=Type"; DO NOT EDIT.

package resource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceCode-0]
	_ = x[CompiledBinary-1]
	_ = x[CompileOutput-2]
	_ = x[TestInput-3]
	_ = x[TestAnswer-4]
	_ = x[TestOutput-5]
	_ = x[TestStderr-6]
	_ = x[Checker-7]
	_ = x[CheckerOutput-8]
	_ = x[Interactor-9]
}

const _Type_name = "SourceCodeCompiledBinaryCompileOutputTestInputTestAnswerTestOutputTestStderrCheckerCheckerOutputInteractor"

var _Type_index = [...]uint8{0, 10, 24, 37, 46, 56, 66, 76, 83, 96, 106}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
